/* Regression guards for the lazy-loaded per-letter bin detail (docs/data/comments/<acc>.json),
 * generated by tools/build-comments-page-data.mjs and fetched by the Comments tab when a row's
 * analysis is opened. The detail is the audit trail the UI shows: each bin's description + the
 * verbatim quotes it draws on. These tests pin it to its source (sources/comments/summaries-v2/)
 * so a stale build, a dropped letter, or an edited/fabricated quote fails CI — not the browser.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { VOCAB } from "../tools/validate-summaries.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, "..");
const DETAIL = join(ROOT, "docs", "data", "comments");
const V2 = join(ROOT, "sources", "comments", "summaries-v2");

const detailFiles = existsSync(DETAIL) ? readdirSync(DETAIL).filter((f) => f.endsWith(".json")) : [];
const v2Files = readdirSync(V2).filter((f) => f.endsWith(".json"));
const manifest = JSON.parse(readFileSync(join(ROOT, "sources", "comments", "rm26-4-comments.json"), "utf8"));
const manifestAccs = new Set(manifest.comments.map((c) => c.acc));
const loadDetail = (f) => JSON.parse(readFileSync(join(DETAIL, f), "utf8"));
const loadV2 = (acc) => JSON.parse(readFileSync(join(V2, acc + ".json"), "utf8"));

// the v2 summaries that the builder emits detail for: every one whose accession is in the manifest
const expectedAccs = v2Files.map((f) => f.slice(0, -5)).filter((acc) => manifestAccs.has(acc));

test("one detail file per audited letter (count floor, append-only — never silently drops)", () => {
  assert.ok(detailFiles.length >= 260, `detail count floor (${detailFiles.length} >= 260)`);
  assert.equal(detailFiles.length, expectedAccs.length,
    `one detail file per manifest-listed v2 summary (${detailFiles.length} === ${expectedAccs.length})`);
});

test("every audited letter has a detail file, and every detail file maps to a v2 summary", () => {
  const have = new Set(detailFiles.map((f) => f.slice(0, -5)));
  const missing = expectedAccs.filter((acc) => !have.has(acc));
  assert.deepEqual(missing, [], `letters missing a detail file: ${missing.join(", ")}`);
  const orphans = [...have].filter((acc) => !existsSync(join(V2, acc + ".json")));
  assert.deepEqual(orphans, [], `detail files with no source summary: ${orphans.join(", ")}`);
});

test("each detail file matches the documented schema exactly (no extra fields)", () => {
  for (const f of detailFiles) {
    const d = loadDetail(f);
    assert.deepEqual(Object.keys(d).sort(), ["acc", "bins"], `${f} has exactly {acc, bins}`);
    assert.equal(d.acc + ".json", f, `${f} acc field matches filename`);
    assert.ok(Array.isArray(d.bins), `${f} bins is an array`);
    for (const b of d.bins) {
      assert.deepEqual(Object.keys(b).sort(), ["desc", "key", "name", "pages", "quotes", "stance"],
        `${f} bin ${b.key} has exactly {key,name,stance,desc,quotes,pages}`);
      assert.ok(b.key && b.name, `${f} bin has key + name`);
      assert.ok(VOCAB.STANCES.has(b.stance), `${f} bin ${b.key} stance "${b.stance}" is valid`);
      assert.equal(typeof b.desc, "string", `${f} bin ${b.key} desc is a string`);
      assert.ok(Array.isArray(b.quotes), `${f} bin ${b.key} quotes is an array`);
      for (const q of b.quotes) assert.ok(typeof q === "string" && q.length > 0, `${f} bin ${b.key} quote is non-empty`);
      assert.ok(Array.isArray(b.pages) && b.pages.length === b.quotes.length, `${f} bin ${b.key} pages parallels quotes`);
      for (const p of b.pages) assert.ok(p === null || (Number.isInteger(p) && p >= 1), `${f} bin ${b.key} page is a positive int or null`);
    }
  }
});

test("detail bins + quotes trace verbatim to the source summary (no drift, no fabrication)", () => {
  for (const f of detailFiles) {
    const d = loadDetail(f);
    const s = loadV2(d.acc);
    assert.equal(d.bins.length, (s.bins || []).length, `${f} bin count matches source`);
    const qById = Object.fromEntries((s.quotes || []).map((q) => [q.id, q]));
    s.bins.forEach((sb, i) => {
      const db = d.bins[i];
      assert.equal(db.key, sb.key, `${f} bin ${i} key matches source (order preserved)`);
      assert.equal(db.name, sb.name, `${f} bin ${sb.key} name matches source`);
      assert.equal(db.stance, sb.stance, `${f} bin ${sb.key} stance matches source`);
      assert.equal(db.desc, sb.description || "", `${f} bin ${sb.key} description matches source`);
      // quotes are the resolved source quote texts, in quote_ids order, byte-for-byte (verbatim);
      // pages parallel them, each the source quote's stamped page.
      const qs = (sb.quote_ids || []).map((id) => qById[id]).filter(Boolean);
      assert.deepEqual(db.quotes, qs.map((q) => q.text), `${f} bin ${sb.key} quotes are the verbatim source quotes`);
      assert.deepEqual(db.pages, qs.map((q) => (q.page == null ? null : q.page)), `${f} bin ${sb.key} pages trace to source`);
    });
  }
});
