/* Trace-back guards for the By-issue index (docs/data/comments/issues/), generated by
 * tools/build-comments-page-data.mjs. The By-issue reader inverts the per-letter bins into one file
 * per issue; these tests pin that inversion to its source (the per-letter detail files, which are
 * themselves pinned to sources/comments/summaries-v2/ by comment-detail.test.mjs) so a stale build,
 * a dropped bin, or an edited quote fails CI — not the browser. Plan §1.3.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, "..");
const DETAIL = join(ROOT, "docs", "data", "comments");
const ISSUES = join(DETAIL, "issues");

const canonStance = (s) => { s = String(s); return /support/i.test(s) ? "support" : /oppose/i.test(s) ? "oppose" : /mixed/i.test(s) ? "mixed" : "neutral"; };
const nsOf = (key) => String(key).split(":")[0];
const CONTROLLED = new Set(["aq", "pr", "rg"]);

// the per-letter detail files (authoritative source the UI lazy-loads for a single letter)
const detailFiles = readdirSync(DETAIL).filter((f) => f.endsWith(".json"));
const details = detailFiles.map((f) => JSON.parse(readFileSync(join(DETAIL, f), "utf8")));

// the By-issue index: one outline (index.json) + one file per surfaced issue
const outline = JSON.parse(readFileSync(join(ISSUES, "index.json"), "utf8"));
const issueFiles = readdirSync(ISSUES).filter((f) => f.endsWith(".json") && f !== "index.json");
const loadIssue = (slug) => JSON.parse(readFileSync(join(ISSUES, slug + ".json"), "utf8"));

// comments-data.js — the up-front list, source of each row's org + bucket
const cdCtx = { window: {} };
vm.createContext(cdCtx);
vm.runInContext(readFileSync(join(ROOT, "docs", "js", "comments-data.js"), "utf8"), cdCtx);
const rowByAcc = Object.fromEntries(cdCtx.window.FERC_COMMENTS.list.map((c) => [c.acc, c]));

// expected inversion, built independently from the per-letter detail files
const expected = {}; // key -> Map(acc -> bin)
for (const d of details) for (const b of d.bins || []) {
  (expected[b.key] = expected[b.key] || new Map()).set(d.acc, b);
}

test("outline and issue files are consistent (one file per entry, slug === filename)", () => {
  assert.ok(outline.length >= 19, `at least the 19 controlled-vocab lenses (got ${outline.length})`);
  assert.equal(outline.length, issueFiles.length, "one issue file per outline entry");
  const fileSlugs = new Set(issueFiles.map((f) => f.slice(0, -5)));
  for (const e of outline) {
    assert.ok(fileSlugs.has(e.slug), `outline entry ${e.key} has a file ${e.slug}.json`);
    assert.equal(nsOf(e.key), e.ns, `ns matches key for ${e.key}`);
  }
  // no duplicate slugs
  assert.equal(new Set(outline.map((e) => e.slug)).size, outline.length, "slugs are unique");
});

test("every controlled-vocab lens (8 aq + 5 pr + 6 rg) is present", () => {
  const lenses = outline.filter((e) => CONTROLLED.has(e.ns));
  assert.equal(lenses.filter((e) => e.ns === "aq").length, 8, "8 ANOPR questions");
  assert.equal(lenses.filter((e) => e.ns === "pr").length, 5, "5 reform principles");
  assert.equal(lenses.filter((e) => e.ns === "rg").length, 6, "6 regions");
});

test("controlled-vocab union is lossless: every aq/pr/rg bin lands in exactly one issue file", () => {
  // forward: every expected controlled-vocab (key, acc) appears in its issue file
  const bySlug = Object.fromEntries(outline.map((e) => [e.key, e.slug]));
  for (const [key, m] of Object.entries(expected)) {
    if (!CONTROLLED.has(nsOf(key))) continue;
    assert.ok(bySlug[key], `controlled-vocab issue ${key} is surfaced`);
    const iss = loadIssue(bySlug[key]);
    const accs = new Set(iss.letters.map((l) => l.acc));
    assert.equal(accs.size, iss.letters.length, `no duplicate letters in ${key}`);
    for (const acc of m.keys()) assert.ok(accs.has(acc), `${acc} present in issue ${key}`);
    assert.equal(iss.letters.length, m.size, `letter count matches for ${key}`);
  }
  // reverse: no issue file invents a (key, acc) that the source doesn't have
  for (const f of issueFiles) {
    const iss = loadIssue(f.slice(0, -5));
    if (!CONTROLLED.has(nsOf(iss.key))) continue;
    for (const l of iss.letters) assert.ok(expected[iss.key] && expected[iss.key].has(l.acc),
      `issue ${iss.key} letter ${l.acc} traces back to a per-letter bin`);
  }
});

test("bin-for-bin trace-back: stance, description, and verbatim quotes match the source", () => {
  for (const f of issueFiles) {
    const iss = loadIssue(f.slice(0, -5));
    for (const l of iss.letters) {
      const src = expected[iss.key] && expected[iss.key].get(l.acc);
      assert.ok(src, `${iss.key}/${l.acc} exists in the per-letter detail`);
      assert.equal(l.stance, src.stance, `stance matches for ${iss.key}/${l.acc}`);
      assert.equal(l.desc, src.desc || "", `description matches for ${iss.key}/${l.acc}`);
      assert.deepEqual(l.quotes, src.quotes || [], `verbatim quotes match for ${iss.key}/${l.acc}`);
      assert.deepEqual(l.pages, src.pages || [], `page cites match for ${iss.key}/${l.acc}`);
    }
  }
});

test("stance tallies and counts are self-consistent with the letters", () => {
  for (const e of outline) {
    const iss = loadIssue(e.slug);
    assert.equal(e.count, iss.letters.length, `outline count matches file for ${e.key}`);
    const tally = { support: 0, oppose: 0, mixed: 0, neutral: 0, total: 0 };
    for (const l of iss.letters) { tally[canonStance(l.stance)]++; tally.total++; }
    assert.deepEqual(iss.stances, tally, `stance tally matches letters for ${e.key}`);
    assert.deepEqual(e.stances, tally, `outline stances match file for ${e.key}`);
  }
});

test("surfaced emergent topics are recurring (>=3 letters) and capped (<=15)", () => {
  const topics = outline.filter((e) => e.ns === "topic");
  assert.ok(topics.length <= 15, `topics capped at 15 (got ${topics.length})`);
  for (const t of topics) assert.ok(t.count >= 3, `topic ${t.key} recurs (${t.count} >= 3)`);
});

test("every letter carries an org and a bucket consistent with comments-data.js", () => {
  for (const f of issueFiles) {
    const iss = loadIssue(f.slice(0, -5));
    for (const l of iss.letters) {
      const row = rowByAcc[l.acc];
      assert.ok(row, `${l.acc} is a known comment`);
      assert.ok(l.org && l.org === row.org, `org matches for ${l.acc}`);
      assert.equal(l.bucket, row.bucket, `bucket matches for ${l.acc}`);
    }
  }
});
