/* Guards for the §206 procedural clock (D.procedural) rendered on the Overview tab and the masthead chip.
 * The dates are derived and drive a compliance persona's deadlines, so pin them: valid, chronological,
 * cited, and consistent with the periods quoted from the orders (sources/orders-extract.json → deadlines). */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(readFileSync(join(here, "..", "docs", "js", "data.js"), "utf8"), ctx);
const D = ctx.window.FERC_DATA;
const P = D.procedural;

const isISO = (s) => /^\d{4}-\d{2}-\d{2}$/.test(s);
const days = (a, b) => Math.round((new Date(b + "T00:00:00") - new Date(a + "T00:00:00")) / 86400000);

test("procedural clock exists and is attributed", () => {
  assert.ok(P, "D.procedural is present");
  assert.ok(isISO(P.issued), "issued is an ISO date");
  assert.ok(P.source && D.SOURCES[P.source], "the derived-date source resolves in SOURCES");
  assert.ok(Array.isArray(P.steps) && P.steps.length >= 5, "at least the five clock steps");
});

test("every step is fully authored (label, period, cite, description)", () => {
  for (const s of P.steps) {
    for (const f of ["id", "label", "period", "cite", "desc"]) {
      assert.ok(s[f] && String(s[f]).trim(), `${s.id || "step"} has a ${f}`);
    }
  }
  assert.equal(new Set(P.steps.map((s) => s.id)).size, P.steps.length, "step ids are unique");
});

test("dated steps are valid, on/after issuance, and chronological", () => {
  const dated = P.steps.filter((s) => s.date);
  assert.ok(dated.length >= 4, "most steps carry a derived date");
  let prev = P.issued;
  for (const s of dated) {
    assert.ok(isISO(s.date), `${s.id} date is ISO`);
    assert.ok(days(P.issued, s.date) >= 0, `${s.id} is on/after issuance`);
    assert.ok(days(prev, s.date) >= 0, `${s.id} is not before the previous step`);
    prev = s.date;
  }
});

test("the relative response window has no fixed date (it opens after the 60-day filing)", () => {
  const resp = P.steps.find((s) => s.id === "response");
  assert.ok(resp, "a response-window step exists");
  assert.equal(resp.date, null, "response window is intentionally undated");
  assert.ok(/filing/i.test(resp.dateNote || ""), "its note explains it is relative to the filing");
});

test("the derived dates match the periods quoted from the orders (21/30/45/60 days)", () => {
  const byId = Object.fromEntries(P.steps.map((s) => [s.id, s]));
  // business-day roll can push a date a day or two past the raw period; allow a small window
  const near = (id, period) => { const d = days(P.issued, byId[id].date); assert.ok(d >= period && d <= period + 3, `${id} ≈ ${period} days (got ${d})`); };
  near("intervene", 21);
  near("report", 30);
  near("abeyance", 45);
  near("showcause", 60);
});

test("the two-clocks collision callout is derived from the data, not written into the copy", () => {
  // This paragraph hardcoded "August 17" and kept asserting it after FERC moved BOTH clocks to
  // November, so it shipped a false statement on the Overview tab. It is now derived from the
  // operative show-cause date and the E-2 track's own next date. Guard the invariant it rests on:
  // whenever the two coincide the app must be able to name that date from the data alone.
  const app = readFileSync(join(here, "..", "docs", "js", "app.js"), "utf8");
  // Assert the SUBSTANCE, not one string's exact shape: no calendar date may be written into a display
  // string in app.js at all. Every date the app shows comes from data.js through fmtISO. (PROC_MON is
  // the month-name table fmtISO itself uses, so it is excluded.)
  // The one date that may be written by hand is the orders' own issuance, which is a fixed historical
  // anchor and cannot move. Every other calendar date must come from data.js through fmtISO, because
  // every other one is a deadline and deadlines move. (PROC_MON is fmtISO's own month table.)
  const issued = new RegExp(P.issuedLabel.replace(/,.*$/, "").replace(/\s+/g, "\\s+"));
  const MONTHS = "January|February|March|April|May|June|July|August|September|October|November|December";
  const displayDates = app
    .split("\n")
    .filter((l) => !/^\s*\/\//.test(l))          // source comments may discuss a date; they render nothing
    .filter((l) => !/PROC_MON\s*=/.test(l))
    .filter((l) => new RegExp(`"[^"]*\\b(${MONTHS})\\s+\\d{1,2}\\b`).test(l))
    .filter((l) => !issued.test(l));
  assert.deepEqual(displayDates, [],
    `only the issuance date (${P.issuedLabel}) may be hardcoded; these lines write a movable date into display copy:\n` +
    displayDates.join("\n"));
  assert.match(app, /function collideNote\(\)/, "the callout is generated by a helper");

  const step = P.steps.find((s) => s.id === "showcause");
  const operative = (step.revised && step.revised.date) || step.date;
  const e2 = D.tracks?.e2?.next?.date;
  assert.ok(operative, "the show-cause step resolves to an operative date");
  assert.ok(e2, "the E-2 track carries its own next date");
  // Not asserting they DO collide (they may legitimately diverge); asserting both are resolvable ISO
  // dates, which is what the derivation needs to be correct either way.
  for (const [label, iso] of [["showcause", operative], ["e2.next", e2]]) {
    assert.match(iso, /^\d{4}-\d{2}-\d{2}$/, `${label} is a plain ISO date the renderer can compare`);
  }
});
