// Bakes crawlable content and freshness dates into docs/index.html + docs/sitemap.xml from data.js.
//
//   node tools/build-seo.mjs          # regenerate
//   node tools/build-seo.mjs --check  # exit non-zero if stale
//
// WHY: every one of the six tab panels ships EMPTY and is filled by app.js. Measured before this
// existed, the served HTML carried 113 words — a masthead, six tab labels and a noscript apology —
// on a site holding 3,500 pages of analysed comment record. Googlebot renders JS on a second,
// budget-limited pass; Bing, most LLM crawlers and every social unfurler largely do not. So the
// richest thing about this site was invisible to the crawlers that matter most for it.
//
// This bakes a real summary into the default-visible Overview panel. app.js replaces that panel on
// first render, so a JS visitor sees the app and a crawler sees the same facts in HTML. That is
// progressive enhancement, not cloaking: the baked text is a strict subset of what the app renders,
// drawn from the same data.js, never keyword-stuffed and never hidden from users.
//
// Same generated-output-plus-sync-test contract as build-llms.mjs and stamp-assets.mjs.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { allDockets, slugFor } from "./build-docket-pages.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://pranava0x0.github.io/FERC-Orders-June-2026/";
const START = "<!-- SEO:START (generated by tools/build-seo.mjs — do not edit by hand) -->";
const END = "<!-- SEO:END -->";

export function loadData(root = ROOT) {
  const ctx = { window: {} };
  vm.createContext(ctx);
  vm.runInContext(readFileSync(join(root, "docs", "js", "data.js"), "utf8"), ctx, { filename: "data.js" });
  return ctx.window.FERC_DATA;
}

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

// The baked block. Headings are real headings, links are real links, and every sentence here also
// appears in the rendered app — so a crawler and a reader are being told the same thing.
export function buildSeoBlock(D) {
  const m = D.meta;
  const out = [];
  out.push(START);
  out.push('<div class="seo-static" id="seo-static">');
  out.push(`<h2>${esc(m.title)}: what this is</h2>`);
  for (const p of m.summary) out.push(`<p>${esc(p)}</p>`);

  if (D.tracks) {
    out.push("<h2>Where things stand</h2>");
    out.push(`<p>Four proceedings and one context lane run beside each other, each on its own clock. Status as of ${esc(m.newsCapture || m.capture)}.</p>`);
    out.push("<ul>");
    for (const [, t] of Object.entries(D.tracks)) {
      const next = t.next && t.next.date ? ` Next: ${esc(t.next.date)}, ${esc(t.next.label)}.` : "";
      out.push(`<li><strong>${esc(t.label)}</strong>${t.venue ? ` (${esc(t.venue)})` : ""}. ${esc(t.status.line)}${next}</li>`);
    }
    out.push("</ul>");
  }

  // Link the per-docket pages, not the PDFs. These are the crawl paths into the seven detail pages;
  // each of those then links to its own PDF and to ferc.gov.
  out.push("<h2>The six show cause orders</h2>");
  out.push("<p>Each order has its own page below, with the quoted directives, the region-specific findings and the full respondent roster. Every PDF is a committed copy of the ferc.gov original, served with this site so page-precise citations open inline.</p>");
  out.push("<ul>");
  for (const d of D.dockets) {
    out.push(
      `<li><a href="dockets/${slugFor(d)}/">${esc(d.item)} ${esc(d.rto)}, Docket ${esc(d.docket)}</a>: ` +
        `${esc(d.cite)}, ${d.pages} pp. ${esc(d.status)}. Region: ${esc(d.region)}. ${esc(d.unique)}</li>`,
    );
  }
  out.push("</ul>");
  if (D.colocation) {
    out.push(
      `<p>Decided the same morning: <a href="dockets/${slugFor(D.colocation)}/">${esc(D.colocation.item)} ` +
        `(Docket ${esc(D.colocation.docket)}, ${esc(D.colocation.cite)})</a>, the PJM co-location order on ` +
        `rehearing that finalises the three new transmission services the six orders extend.</p>`,
    );
  }

  out.push("<h2>The five reform categories</h2>");
  out.push("<ul>");
  for (const c of D.categories) out.push(`<li><strong>${esc(c.title)}</strong>: ${esc(c.ferc)}</li>`);
  out.push("</ul>");

  if (D.procedural && D.procedural.steps) {
    out.push("<h2>The §206 procedural clock</h2>");
    out.push(`<p>${esc(D.procedural.basis)}</p>`);
    out.push("<ul>");
    for (const s of D.procedural.steps) {
      out.push(`<li><strong>${esc(s.date || "Not yet dated")}</strong>, ${esc(s.label)} (${esc(s.period)}, ${esc(s.cite)}): ${esc(s.desc)}</li>`);
    }
    out.push("</ul>");
  }

  out.push(
    `<p>This is an independent analysis microsite and is not affiliated with FERC or DOE. ` +
      `Order record as of ${esc(m.capture)}; commentary ${esc(m.discourseCapture)}` +
      (m.newsCapture ? `; news and filings swept ${esc(m.newsCapture)}` : "") +
      `. A machine-readable index for agents is at <a href="llms.txt">llms.txt</a>.</p>`,
  );
  out.push("</div>");
  out.push(END);
  return out.join("\n");
}

function replaceBetween(html, block) {
  const i = html.indexOf(START);
  const j = html.indexOf(END);
  if (i === -1 || j === -1) {
    // First run: inject into the default-visible Overview panel.
    const panel = '<section class="panel" role="tabpanel" id="panel-overview" aria-labelledby="tab-overview" tabindex="0">';
    if (!html.includes(panel)) throw new Error("could not find the Overview panel to bake into");
    return html.replace(panel, `${panel}\n${block}\n    `);
  }
  return html.slice(0, i) + block + html.slice(j + END.length);
}

export function buildIndexHtml(html, D) {
  let out = replaceBetween(html, buildSeoBlock(D));
  const fresh = D.meta.newsCapture || D.meta.discourseCapture || D.meta.capture;

  // Freshness signals. These were hand-typed and had drifted a month behind the data.
  out = out.replace(/("dateModified":\s*")[^"]*(")/, `$1${fresh}$2`);
  out = out.replace(
    /(<meta property="og:description" content="[^"]*?As of )\d{4}-\d{2}-\d{2}(\.")/,
    `$1${fresh}$2`,
  );

  // The social card: twitter:card declared summary_large_image with no image at all, so shares
  // unfurled blank. Insert the tags once, right after the twitter:card line.
  if (!out.includes('property="og:image"')) {
    const anchor = '<meta name="twitter:card" content="summary_large_image" />';
    out = out.replace(
      anchor,
      `${anchor}\n  <meta property="og:image" content="${SITE}og-card.png" />\n` +
        `  <meta property="og:image:width" content="1200" />\n` +
        `  <meta property="og:image:height" content="630" />\n` +
        `  <meta property="og:image:alt" content="Large Load Interconnection: six tailored FERC section 206 show cause orders, Items E-7 to E-12" />\n` +
        `  <meta name="twitter:image" content="${SITE}og-card.png" />`,
    );
  }

  // The comment corpus is a genuine structured dataset (every filing scraped, text-extracted and
  // quote-binned), and Dataset is a rich-result type the Report entity above does not cover. Declared
  // once, after the existing JSON-LD block, and regenerated so its counts cannot drift from the data.
  const DATASET_MARK = '"@type": "Dataset"';
  const dataset =
    `  <script type="application/ld+json">\n` +
    JSON.stringify(
      {
        "@context": "https://schema.org",
        "@type": "Dataset",
        name: "RM26-4-000 public comment record, quote-binned",
        description:
          `All ${D.comments.filings} filings in FERC Docket RM26-4-000 scraped from eLibrary, with ` +
          `${D.comments.total} public comments text-extracted and summarised the auditable way: verbatim ` +
          `quotes binned to the five reform principles, the eight ANOPR questions and the six RTO regions, ` +
          `each bin carrying the filer's own stance. AI-generated and provisional, with every quote ` +
          `traceable to its source filing.`,
        url: `${SITE}#comments`,
        creator: { "@type": "Organization", name: "Independent regulatory analysis" },
        dateModified: fresh,
        isAccessibleForFree: true,
        license: "https://github.com/pranava0x0/FERC-Orders-June-2026",
        keywords: ["FERC", "RM26-4-000", "large load interconnection", "data centers", "public comments"],
        measurementTechnique: "eLibrary scrape, text extraction, LLM quote extraction with deterministic verbatim validation",
      },
      null,
      2,
    ) +
    `\n  </script>`;
  // Replace an existing Dataset script tag in place (its dateModified must track fresh sweeps, not just
  // get baked once and left stale forever); only fall back to inserting before </head> the first time.
  // Leading whitespace is part of the match (not just `<script...>` onward) so a re-run replaces the
  // WHOLE indented block including its own indent, rather than leaving the old indent in front of the
  // freshly-templated one and compounding it deeper on every regeneration.
  const scriptRe = /[ \t]*<script type="application\/ld\+json">\n[\s\S]*?\n[ \t]*<\/script>/g;
  let replaced = false;
  out = out.replace(scriptRe, (block) => {
    if (replaced || !block.includes(DATASET_MARK)) return block;
    replaced = true;
    return dataset;
  });
  if (!replaced) out = out.replace("</head>", `${dataset}\n</head>`);
  return out;
}

// Generated whole rather than patched, so a new docket page cannot be added and left out of it.
// The root and the docket pages track the news sweep; the order PDFs keep their issuance date.
export function buildSitemap(D) {
  const fresh = D.meta.newsCapture || D.meta.capture;
  const rows = [`  <url>\n    <loc>${SITE}</loc>\n    <lastmod>${fresh}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>1.0</priority>\n  </url>`];
  for (const d of allDockets(D)) {
    rows.push(
      `  <url><loc>${SITE}dockets/${slugFor(d)}/</loc><lastmod>${fresh}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url>`,
    );
  }
  for (const d of allDockets(D)) {
    rows.push(`  <url><loc>${SITE}${d.pdf}</loc><lastmod>2026-06-18</lastmod><priority>0.6</priority></url>`);
  }
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${rows.join("\n")}\n</urlset>\n`;
}

if (process.argv[1] && process.argv[1] === fileURLToPath(import.meta.url)) {
  const D = loadData();
  const htmlPath = join(ROOT, "docs", "index.html");
  const mapPath = join(ROOT, "docs", "sitemap.xml");
  const html = readFileSync(htmlPath, "utf8");
  const xml = readFileSync(mapPath, "utf8");
  const nextHtml = buildIndexHtml(html, D);
  const nextXml = buildSitemap(D);

  if (process.argv.includes("--check")) {
    const stale = [];
    if (html !== nextHtml) stale.push("docs/index.html");
    if (xml !== nextXml) stale.push("docs/sitemap.xml");
    if (stale.length) {
      console.error(`SEO content is stale (${stale.join(", ")}). Regenerate with: node tools/build-seo.mjs`);
      process.exit(1);
    }
    console.log("SEO content is in sync.");
  } else {
    writeFileSync(htmlPath, nextHtml);
    writeFileSync(mapPath, nextXml);
    const words = buildSeoBlock(D).replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
    console.log(`Baked ~${words} crawlable words into docs/index.html; sitemap lastmod set to ${D.meta.newsCapture}.`);
  }
}
